[[redirects]]
  from = "https://ws.bus.go.kr/*"
  to = "https://www.example.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://ws.bus.go.kr/*"
  to = "http://ws.bus.go.kr/:splat"
  status = 301
  force = true